/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as RouteRouteImport } from './routes/$route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServiceServiceIdRouteImport } from './routes/service.$serviceId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const RouteRoute = RouteRouteImport.update({
  id: '/$route',
  path: '/$route',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceServiceIdRoute = ServiceServiceIdRouteImport.update({
  id: '/service/$serviceId',
  path: '/service/$serviceId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$route': typeof RouteRoute
  '/admin': typeof AdminRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/service/$serviceId': typeof ServiceServiceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$route': typeof RouteRoute
  '/admin': typeof AdminRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/service/$serviceId': typeof ServiceServiceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$route': typeof RouteRoute
  '/admin': typeof AdminRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/service/$serviceId': typeof ServiceServiceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$route'
    | '/admin'
    | '/privacy'
    | '/terms'
    | '/service/$serviceId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$route' | '/admin' | '/privacy' | '/terms' | '/service/$serviceId'
  id:
    | '__root__'
    | '/'
    | '/$route'
    | '/admin'
    | '/privacy'
    | '/terms'
    | '/service/$serviceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RouteRoute: typeof RouteRoute
  AdminRoute: typeof AdminRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  ServiceServiceIdRoute: typeof ServiceServiceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$route': {
      id: '/$route'
      path: '/$route'
      fullPath: '/$route'
      preLoaderRoute: typeof RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service/$serviceId': {
      id: '/service/$serviceId'
      path: '/service/$serviceId'
      fullPath: '/service/$serviceId'
      preLoaderRoute: typeof ServiceServiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RouteRoute: RouteRoute,
  AdminRoute: AdminRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  ServiceServiceIdRoute: ServiceServiceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts.bak'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
